### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000003",
  "amount":100
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "79042662a7d94f51b23dd7d7c1d1c34c",
  "accountNumber": "1000000003",
  "amount":100
}